site_name: Isha English
site_url: https://platform.ishaenglish.com/
repo_url: https://github.com/AlexFreik/isha-english/

theme:
    name: material
    language: ru # The build's language

    features:
        - navigation.tracking
        - navigation.tabs
        - content.action.edit
        - content.action.view
        - navigation.path

    palette:
        - media: '(prefers-color-scheme: light)' # Palette toggle for light mode
          scheme: default
          primary: indigo
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode

        - media: '(prefers-color-scheme: dark)' # Palette toggle for dark mode
          scheme: slate
          primary: indigo
          toggle:
              icon: material/brightness-4
              name: Switch to light mode

extra:
    alternate:
        - name: Русский
          link: /isha-english/
          lang: ru

extra_javascript:
    - js/extra.js

plugins:
    - search:
          lang: ru # Set language for search

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - attr_list
    - md_in_html

nav:
    - 'index.md'
    - 'Theory.md'
    - 'Vocabulary.md'
    - 'Уроки':
          - 'lessons/montage-apps.md'
          - 'lessons/text-translation-methods.md'
